extra_prepare_dict:
    extra_qconfig_dict:
        w_observer: MinMaxObserver
        a_observer: EMAMinMaxObserver
        w_fakequantize: FixedFakeQuantize
        a_fakequantize: FixedFakeQuantize
        w_qscheme:
            bit: 6
            symmetry: False
            per_channel: True
            pot_scale: False
        a_qscheme:
            bit: 6
            symmetry: False
            per_channel: False
            pot_scale: False
quantize:
    smoothquant:
        enabled: false
        alpha: 0
    quantize_type: naive_ptq
    cali_batchsize: 16
model:
    type: resnet18
    kwargs:
        num_classes: 1000
    path: /home/users/ntu/sooq0001/mydir/resnet18_imagenet.pth.tar
data:
    path: /home/users/ntu/sooq0001/scratch/ImageNet-ILSVRC2012/
    batch_size: 64
    num_workers: 4
    pin_memory: True
    input_size: 224
    test_resize: 256
process:
    seed: 1005
